### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by magreen-8da** [dternyak/React-Redux-Flask#43]
I'm getting this build error when I run `npm install` in the `static` directory:

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/Documents/workspace/github/React-Redux-Flask/static/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.4.14-1-default
gyp ERR! command "/usr/bin/node12" "/home/user/Documents/workspace/github/React-Redux-Flask/static/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/user/Documents/workspace/github/React-Redux-Flask/static/node_modules/node-sass
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN notsup Unsupported engine for karma@1.7.1: wanted: {"node":"0.10 || 0.12 || 4 || 5 || 6 || 7 || 8"} (current: {"node":"12.14.1","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: karma@1.7.1
npm WARN eslint-config-airbnb@13.0.0 requires a peer of eslint-plugin-jsx-a11y@^2.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN expose-loader@0.7.5 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-forms@2.0.0-beta9 requires a peer of react@^0.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-stylesheet@0.7.1 requires a peer of react@^0.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN redux-easy-boilerplate@1.3.3 No description
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-02-07T22_54_32_868Z-debug.log
```

Would you give me some pointers how to resolve this? I'm new so it will probably take me a very long time to unwind this. It seems like there's some version mismatch and missing packages; does it need node version 12.0 exactly or version 8 exactly? Why is 12.14.1 not good enough? Thanks,

**Comment by samrudh** [comment]
Install the node-sass module as mentioned below. And then run npm install, npm start.

`npm install node-sass@latest`

`  npm install`

`  npm start`

**Comment by alejandroarmas** [comment]
Thanks! @samrudh
